"""empty message

Revision ID: f897a6dde79b
Revises: b2e62db6eb06
Create Date: 2023-03-19 12:46:17.552827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f897a6dde79b'
down_revision = 'b2e62db6eb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.drop_column('last')
        batch_op.drop_column('first')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))
        batch_op.drop_column('last')
        batch_op.drop_column('first')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
